---
- name: create nfs mount points
  file:
    path: "{{ nfs_mountpoint }}"
    state: directory

- name: configure nfs mount
  mount:
    path: "{{ nfs_mountpoint }}"
    src: "{{ nfs_share }}"
    fstype: "{{ nfs_fstype | default('nfs') }}"
    opts: "{{ nfs_opts | default('defaults') }}"
    state: present
...
