---
- name: Add cron job to run Linux Veeam Server install Script on reboot
  cron:
    name: "Linux Veeam Server install Script on reboot"
    special_time: reboot
    job: "sh /usr/local/sbin/vm-install-script.sh"
...
