---
- name: Add cron job to run Linux Veeam Server install Script on reboot
  cron:
    name: "Linux Veeam Server install Script on reboot"
    special_time: reboot
    job: "sh /etc/ansible/roles/uniQconsulting.veeam_linux_repo/tests/cos7-veeam-repo-install.sh"
...
