---
- name: install veeam dependencies
  yum:
    name: '{{ item.package }}'
    state: present
  with_items: '{{ cos7_veeam_dependencies }}'
- name: add cronjob to monitor running Veeam jobs
  copy:
    dest: "/etc/cron.d/veeam-counter"
    mode: 0644
    owner: root
    group: root
    content: "*/10 * * * * {{ veeam_user_name }} /usr/bin/logger -t veeam-counter \"$(/usr/bin/pgrep -fla VeeamAgent | grep -v 'logger -t veeam-counter' | /bin/cut -d/  -f7 | tr '\\n' ' ' )\""
- name: reload crond
  service:
    name: crond
    state: reloaded
- name: create log folder for veeam
  file:
    path: /var/log/VeeamBackup
    state: directory
    mode: 0755
    owner: "{{ veeam_user_name }}"
    group: "{{ veeam_user_name }}"
