---
# tasks file for uniQconsulting.veeam_linux_repo
- name: include role
  include_role:
    name: uniqconsulting.os_basic
  vars:
    epel_repo: true
    setup_selinux: true
    selinux_policy: 'permissive'
    setup_firewalld: true
    setup_iptables: false
